version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_nest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: topicos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  pgdata:

networks:
  nest-network:
